spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password: 123456a!A
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8282
